#!/bin/bash

# Array to hold our values. An 'L' is stored as negative, an 'R' as positive.
values=()

while read -r val; do
	quant="${val:1}"
	if [[ "${val:0:1}" == "L" ]]; then
		quant=$((-quant))
	fi
	values+=($quant)
done

dial=50
count=0
for val in "${values[@]}"; do
	# We're going to adjust the dial either the $val amount, or until it gets to zero
	if [[ $((dial % 100)) -ne 0 ]]; then
		if [[ $val -ge 0 ]]; then
			adjustment_val=$(( (100-dial) >= val ? val : (100-dial) ))
			((dial+=adjustment_val))
			((val-=adjustment_val))
			if [[ $dial -eq 0 || $dial -eq 100 ]]; then
				((count+=1))
				dial=0
			fi
		else
			adjustment_val=$(( dial >= -val ? -val : dial ))
			((dial-=adjustment_val))
			((val+=adjustment_val))
			if [[ $dial -eq 0 || $dial -eq 100 ]]; then
				((count+=1))
				dial=0
			fi
		fi
	fi

	# val may be zero if the dial didn't reach 0, or is the remaining amount to turn
	# dial after it reaches 0 for the first time (sign is preserved)
	if [[ $val -eq 0 ]]; then
		continue
	fi

	# todo: count loops around 0 and then adjust final dial value
	quotient=$((val / 100))
	remainder=$((val % 100))
	quotient=$(( quotient < 0 ? -quotient : quotient ))
	remainder=$(( remainder < 0 ? remainder + 100 : remainder ))

	((count+=quotient))
	dial=$remainder
done

echo "Password is $count"
