#!/bin/bash

# Array to hold our values. An 'L' is stored as negative, an 'R' as positive.
values=()

while read -r val; do
	quant="${val:1}"
	if [[ "${val:0:1}" == "L" ]]; then
		quant=$((-quant))
	fi
	values+=($quant)
done

dial=50
count=0
for val in "${values[@]}"; do
	# Need to force the math modulo
	dial=$(( ( (dial + val) % 100 + 100 ) % 100 ))
	if [[ $dial -eq 0 ]]; then
		count=$((count+1))
	fi
done

echo "Password is $count"
