#!/bin/bash

# Use stdin to get values

find_length() {
	l=$1
	w=$2
	h=$3

	# get each unique face perimiter
	local p1=$((2 * l + 2 * w))
	local p2=$((2 * w + 2 * h))
	local p3=$((2 * h + 2 * l))

	local min_p=$(( p1 < p2 ? p1 : p2 ))
	local min_p=$(( min_p < p3 ? min_p : p3 ))

	local volume=$((l * w * h))
	local length=$((min_p + volume))

	echo $length
}

total_length=0
while read -r line; do
	IFS='x' read -r l w h <<< "$line"
	current_length=$(find_length $l $w $h)
	((total_length+=current_length))
done

echo "Total length of ribbon = $total_length"
